# This is a basic workflow to help you get started with Actions

name: Release trigger

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  release:
    types:
      - published
      - prereleased
      - released
      - created  # temporary for dev
      - edited   # temporary for dev

env:
  OWNER_NAME: dzeyelid
  REPOSITORY_NAME: playground-dispatch-event-receiver
  WORKFLOW_NAME: workflow-dispatch.yml
  TARGET_BRANCH: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Show event
        run: echo "${{ toJson(github.event) }}"
      - name: Test
        uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/:repository/releases
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output
        run: echo "${{ toJson(steps.get_latest_release.outputs) }}"        

      - name: Run workflow_dispatch
        uses: octokit/request-action@v2.x
        id: release_trigger
        with:
          route: POST /repos/:owner/:repository/actions/workflows/:workflow/dispatches
          mediaType: |
            format: application/vnd.github.v3+json
          owner: ${{ env.OWNER_NAME }}
          repository: ${{ env.REPOSITORY_NAME }}
          workflow: ${{ env.WORKFLOW_NAME }}
          ref: ${{ env.TARGET_BRANCH }}
          inputs: |
            release_tag: test
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Output
        run: echo "${{ toJson(steps.release_trigger.outputs) }}"        
